// ═══════════════════════════════════════════════════════════════════════════
// ProjectAssure — Plain-language glossary.
// Every technical term used in the app, explained for a first-time visitor.
// Rendered by the Help Centre (Help view) and the InfoTip tooltips.
// ═══════════════════════════════════════════════════════════════════════════
import type { GlossaryTerm } from "./types";

export const GLOSSARY: GlossaryTerm[] = [
  // ── metrics ──────────────────────────────────────────────────────────────
  { id: "g-health", term: "Project Health Score", category: "metric",
    plain: "A 0–100 score for how well a project is doing — like a report card.",
    detail: "Built from four parts: schedule (30%), budget (25%), resources (20%) and milestones (25%). Above 75 = healthy (green), 50–75 = needs attention (amber), below 50 = critical (red). The score is recomputed after every change, so it always reflects the latest data.",
    where: "Dashboard, project cards, Project → Overview" },
  { id: "g-pai", term: "Assurance Index (PAI)", category: "metric",
    plain: "The single number the authority can trust: how sure can we be this project will deliver as promised.",
    detail: "Combines financial discipline, schedule discipline, physical progress, procurement behaviour, compliance and evidence quality into one 0–100 index. High = assured delivery; low = needs intervention.",
    where: "Project → Overview (score dial)" },
  { id: "g-mismatch", term: "Financial–Physical Mismatch", category: "metric",
    plain: "The gap between how much money was spent and how much work was actually built.",
    detail: "Example: 76% of the money spent but only 48% of the work finished = 28% mismatch. A persistent gap is the classic early warning of inflated billing or stalled execution — which is why it drives a priority-1 recommended action.",
    where: "Project → Risk, Dashboard attention list" },
  { id: "g-variance", term: "Variance (Cost / Schedule)", category: "metric",
    plain: "The difference between what was planned and what actually happened.",
    detail: "Cost variance = expected cost − actual cost. Schedule variance = planned date − expected date. Positive/negative signs tell you whether you are ahead or behind — every table in the app shows the sign explicitly.",
    where: "Project → Budget, Baseline vs Actual table" },
  { id: "g-ci", term: "Confidence Range (CI)", category: "metric",
    plain: "The honest error-bar on a prediction — the range the real answer probably falls in.",
    detail: "\"Delay 44 days, CI 24–64\" means the model expects 44 days but the true delay will most likely land between 24 and 64 days. Wider ranges mean more uncertainty — never treat the centre number as a guarantee.",
    where: "Risk tab, predictions, intelligence answers" },
  { id: "g-burn", term: "Burn Velocity", category: "metric",
    plain: "How fast money is being spent compared to plan.",
    detail: "Spending 30%+ faster than the plan trajectory flags a warning, because a project can run out of budget long before it runs out of work.",
    where: "Risk tab, Prediction Engine feature list" },

  // ── machine learning ─────────────────────────────────────────────────────
  { id: "g-model", term: "Prediction Engine", category: "ml",
    plain: "The statistical engine that estimates delay probability and cost overruns.",
    detail: "Trained on project histories with 18 measured features (progress gap, spend gap, milestone slippage, resource strain…). It outputs a probability, never a certainty — which is why every prediction carries a confidence range and a plain-language explanation.",
    where: "Prediction Engine, Risk tab" },
  { id: "g-shap", term: "Driving Factors", category: "ml",
    plain: "A breakdown of exactly which factors pushed the risk score up or down, and by how much.",
    detail: "Instead of a black-box answer, each factor shows its measured value, direction (raises/lowers risk) and weight. This is what makes every prediction explainable — you can audit the reasoning, factor by factor.",
    where: "Project → Risk (factor bars)" },
  { id: "g-features", term: "18 Risk Signals", category: "ml",
    plain: "The 18 numbers the model measures for every project before scoring it.",
    detail: "Includes financial/physical gap, schedule slippage, milestone status, resource utilisation, document freshness, alert history and more. All 18 are listed in Prediction Engine with their current distributions.",
    where: "Prediction Engine → Feature registry" },
  { id: "g-auc", term: "Model Quality Metrics", category: "ml",
    plain: "Grades for the prediction model itself — how accurate it is on held-out data.",
    detail: "Accuracy: how well it separates on-time vs late projects (1.0 = perfect). Average error: predicted vs actual days. Reliability/calibration: whether its stated probabilities are honest. The Prediction Engine shows all of them before/after each retrain.",
    where: "Prediction Engine" },
  { id: "g-whatif", term: "What-If Simulator", category: "ml",
    plain: "A sandbox to ask “if X changed, what would happen to cost and risk?”",
    detail: "Move sliders (material cost, delay, change orders) and the engine re-scores the project under those assumptions before anything real changes. Ideal for testing interventions before approving them.",
    where: "Project → Risk → What-If" },
  { id: "g-champion", term: "Version Rotation", category: "ml",
    plain: "The proven model (champion) vs the newly trained candidate (new version).",
    detail: "A new version only replaces the current one after a shadow evaluation week where it beats the incumbent on accuracy and average error — the same discipline used in production prediction systems.",
    where: "Prediction Engine" },

  // ── process ──────────────────────────────────────────────────────────────
  { id: "g-alert", term: "Alert Rules (R1…R12)", category: "process",
    plain: "Fixed checks that run automatically after every data change.",
    detail: "Examples: budget overrun >20%, delay probability >70%, data staleness >45 days. Each rule has a severity and a channel (in-app only, or in-app + email). R-numbers are their IDs — the Alerts Centre shows each rule with its plain-language description.",
    where: "Alerts Centre, Admin → Rules" },
  { id: "g-verify", term: "Officer Verification (R10)", category: "process",
    plain: "No intelligence conclusion triggers escalation until a human officer has verified it.",
    detail: "Red-flagged projects always require verification by the responsible officer before escalation — the intelligence engine advises, humans decide. Acknowledgements are recorded in the audit trail with name and time.",
    where: "Alerts Centre (Acknowledge), intelligence answers" },
  { id: "g-intervention", term: "Intervention Lifecycle", category: "process",
    plain: "The 7-step journey of an issue: Detected → Reviewed → Action Assigned → Under Investigation → Resolved → Verified → Closed.",
    detail: "Every detected issue can be tracked to closure with owners, deadlines and evidence counts. This is what turns monitoring into governance — problems don't just get noticed, they get finished.",
    where: "Interventions Centre" },
  { id: "g-evidence", term: "Evidence & Verification", category: "process",
    plain: "Site photos, inspection notes and documents that prove progress claims.",
    detail: "A progress number without evidence is just a claim. Uploaded documents are parsed (OCR), summarised and searchable; the Risk tab counts verified evidence explicitly.",
    where: "Project → Documents, Evidence" },
  { id: "g-baseline", term: "Baseline vs Actual", category: "process",
    plain: "The original approved plan, side-by-side with today's reality.",
    detail: "Physical %, financial %, cost and completion date — planned, actual and the variance for each. One glance shows the shape of the drift.",
    where: "Project → Overview table" },
  { id: "g-noaction", term: "No-Action Impact", category: "process",
    plain: "\"What happens if we do nothing?\" — projected risk/cost/delay in 30/60/90 days.",
    detail: "Uses the same drift rates as the prediction model to show the cost of waiting, and contrasts it with the risk level if the recommended interventions are applied.",
    where: "Project → Risk → No-Action Impact" },

  // ── security ─────────────────────────────────────────────────────────────
  { id: "g-hash", term: "Password Protection", category: "security",
    plain: "Your password is never stored — only an irreversible fingerprint of it.",
    detail: "Registration turns your password into a one-way encrypted fingerprint with a unique random salt before anything is stored, and verification compares fingerprints — the plaintext never touches storage.",
    where: "Login/Create account, Admin → Users" },
  { id: "g-rbac", term: "Role-Based Access (RBAC)", category: "security",
    plain: "What you can see and do depends on your role.",
    detail: "Admin: everything. Project Manager: full control of own projects. Stakeholder: review and comment on department projects. Viewer: read-only. Data is filtered per role before rendering — not just hidden buttons.",
    where: "Login role cards, Admin" },
  { id: "g-jwt", term: "Session Token (JWT)", category: "security",
    plain: "A signed pass that lets you stay logged in safely.",
    detail: "Issued at login, signed HS256, valid 24h, and handed off between the Command Centre / Analytics / Intelligence portal views without re-login.",
    where: "Admin → Deployment" },

  // ── platform ─────────────────────────────────────────────────────────────
  { id: "g-rag", term: "Ask-the-Documents (RAG)", category: "platform",
    plain: "Answers come from your uploaded documents, not from imagination.",
    detail: "Documents are split into chunks, embedded into a 256-dimension vector store, and retrieved by similarity to your question — so answers cite the source file and page. Retrieval-Augmented Generation is the industry name.",
    where: "Assure Intelligence, Vector Store" },
  { id: "g-vector", term: "Vector Store", category: "platform",
    plain: "A search index that finds documents by meaning, not just keywords.",
    detail: "Each chunk becomes a numeric vector; cosine similarity measures how close two meanings are. In production this scales to a dedicated search service; the prototype ships a built-in index you can test.",
    where: "Vector Store screen" },
  { id: "g-ocr", term: "Document Reading (OCR)", category: "platform",
    plain: "Turning uploaded files (PDF/scan/photo) into machine-readable text.",
    detail: "The pipeline: extract text → structure fields (validated) → summarise → index for search. Confidence scores flag unreadable pages; low-confidence extractions never silently pass.",
    where: "Reports & Documents (pipeline)" },
  { id: "g-agent", term: "Acting Tools", category: "platform",
    plain: "The assistant can actually DO things — run queries, compute forecasts — not just chat.",
    detail: "Six tools (portfolio query, project stats, prediction lookup, document search, alert list, comparison) are executed for real; each answer shows the tool trace so you can verify what was run.",
    where: "Assure Intelligence (tool trace)" },
  { id: "g-live", term: "Live intelligence mode", category: "platform",
    plain: "Toggle that switches Assure Intelligence from the built-in engine to a connected live intelligence service.",
    detail: "When a live intelligence service is connected, answers come from it (grounded on your live portfolio snapshot). Without it, the built-in engine answers offline — identical questions, both grounded, zero hallucination either way.",
    where: "Assure Intelligence → Live mode toggle" },
  { id: "g-neon", term: "Cloud Database", category: "platform",
    plain: "The secure cloud database where accounts and data are stored in production.",
    detail: "In production, accounts and every project live in a managed secure database. In the offline prototype the same data model runs locally in your browser — switching to the cloud database is a one-line configuration.",
    where: "Admin → Deployment" },
  { id: "g-portal", term: "One Web Address", category: "platform",
    plain: "The whole platform is served at a single secure address.",
    detail: "Deployed as one platform at one web address — officials, analysts and power users each land on their tailored portal view after signing in.",
    where: "Admin → Deployment, landing page" },
  { id: "g-outbox", term: "Email Outbox (demo mode)", category: "platform",
    plain: "When no email provider is configured, emails are recorded honestly as SIMULATED.",
    detail: "The Email Centre always shows what would be sent and to whom. Connecting a real email service switches delivery to real — the app never pretends a simulated send was delivered.",
    where: "Email Centre" },
  { id: "g-events", term: "Live Portfolio Feed", category: "platform",
    plain: "A simulation of field updates arriving in real time (every 40 seconds).",
    detail: "Progress drifts, milestones complete, alerts fire and notifications arrive — exactly the stream a real-time connection would deliver in production. Toggle it in the top bar.",
    where: "Sidebar live feed, top bar" },
];

export function glossaryById(id: string): GlossaryTerm | undefined {
  return GLOSSARY.find(g => g.id === id);
}
