"use client";

// Alerts & Broadcast — aggregated alert feed from the snapshot (severity,
// pathway, project) + REAL broadcast composer (main-app webhook, audience=all)
// + direct user alert (audience=userId). Delivery status is honest.

import { useMemo, useState } from "react";
import { Bell, Megaphone, Radio, Send, UserRound } from "lucide-react";
import { toast } from "sonner";
import { Badge, Button, Card, CardHead, Dialog, EmptyState, FieldLabel, Input, PageIntro, Select, Textarea, severityTone } from "./ui";
import { fmtDateTime, relTime } from "@/lib/host/format";
import type { Severity } from "@/lib/host/types";
import type { ViewProps } from "./view-props";

export function AlertsView({ state, refresh }: ViewProps) {
  const [severityFilter, setSeverityFilter] = useState("all");
  const [broadcastOpen, setBroadcastOpen] = useState(false);
  const [directOpen, setDirectOpen] = useState(false);
  const [busy, setBusy] = useState<string | null>(null);
  const [broadcastForm, setBroadcastForm] = useState({ title: "", message: "", severity: "info" as Severity, linkView: "" });
  const [directForm, setDirectForm] = useState({ userId: "", title: "", message: "", severity: "info" as Severity });

  const alerts = useMemo(
    () => (severityFilter === "all" ? state.mirror.alerts : state.mirror.alerts.filter((a) => a.severity === severityFilter)),
    [state.mirror.alerts, severityFilter],
  );

  async function post(kind: "broadcast" | "user-alert", payload: Record<string, unknown>, close: () => void) {
    setBusy(kind);
    try {
      const res = await fetch("/api/host/admin/broadcast", {
        method: "POST",
        headers: { "Content-Type": "application/json" },
        body: JSON.stringify({ kind, ...payload }),
      });
      const data = (await res.json().catch(() => ({}))) as { ok?: boolean; note?: string; error?: string };
      if (res.ok && data.ok) {
        toast.success(kind === "broadcast" ? "Broadcast queued" : "User alert queued", { description: data.note });
        close();
        if (kind === "broadcast") setBroadcastForm({ title: "", message: "", severity: "info", linkView: "" });
        else setDirectForm((f) => ({ ...f, title: "", message: "" }));
        await refresh(true);
      } else {
        toast.error("Delivery failed", { description: data.note ?? data.error ?? `HTTP ${res.status}` });
      }
    } catch (e) {
      toast.error("Delivery failed", { description: (e as Error).message });
    } finally {
      setBusy(null);
    }
  }

  const recentBroadcasts = state.broadcasts.slice(0, 12);

  return (
    <div className="space-y-4">
      <PageIntro
        title="Alerts & Broadcast"
        description="The portfolio alert feed mirrored from the main app, plus the control tower's outbound channel: broadcasts reach every logged-in main-app user as a real notification within ~20 seconds (they poll the sync hub)."
      />

      <div className="flex flex-wrap gap-2">
        <Button variant="navy" size="sm" onClick={() => setBroadcastOpen(true)}>
          <Megaphone className="h-3.5 w-3.5" /> New broadcast (all users)
        </Button>
        <Button variant="outline" size="sm" onClick={() => setDirectOpen(true)}>
          <UserRound className="h-3.5 w-3.5" /> Direct user alert
        </Button>
      </div>

      <div className="grid gap-4 xl:grid-cols-3">
        {/* alert feed */}
        <Card className="xl:col-span-2">
          <CardHead
            title="Aggregated alert feed"
            subtitle={`${alerts.length} alerts in the current snapshot (open portfolio-wide: ${state.mirror.stats?.openAlerts ?? 0})`}
            icon={<Bell className="h-4 w-4" />}
            right={
              <Select value={severityFilter} onChange={(e) => setSeverityFilter(e.target.value)} aria-label="Filter by severity" className="h-8 text-xs">
                <option value="all">All severities</option>
                <option value="critical">critical</option>
                <option value="warning">warning</option>
                <option value="info">info</option>
              </Select>
            }
          />
          <div className="host-scroll max-h-[32rem] divide-y divide-slate-100 overflow-y-auto dark:divide-slate-800">
            {alerts.length === 0 ? (
              <div className="p-6">
                <EmptyState
                  icon={<Bell className="h-8 w-8" />}
                  title={severityFilter === "all" ? "No alerts mirrored yet" : `No ${severityFilter} alerts`}
                  hint="Alerts are generated by the main app's monitoring rules — they land here the moment the snapshot updates."
                />
              </div>
            ) : (
              alerts.map((a) => (
                <div key={a.id} className="flex items-start gap-3 px-5 py-3">
                  <Badge tone={severityTone(a.severity)}>{a.severity}</Badge>
                  <div className="min-w-0 flex-1">
                    <p className="truncate text-xs font-medium text-slate-800 dark:text-slate-100">{a.title}</p>
                    <p className="mt-0.5 text-[10px] text-slate-400">
                      {a.projectName ?? a.projectPsId ?? "portfolio-level"} · pathway {a.pathway} · {a.status}
                    </p>
                  </div>
                  <div className="shrink-0 text-right">
                    <p className="text-[10px] text-slate-400">{relTime(a.createdAt)}</p>
                    <p className="text-[9px] text-slate-300">{fmtDateTime(a.createdAt)}</p>
                  </div>
                </div>
              ))
            )}
          </div>
        </Card>

        {/* broadcast log */}
        <Card>
          <CardHead title="Outbound command log" subtitle="what this control tower has queued on the main hub" icon={<Radio className="h-4 w-4" />} />
          <div className="host-scroll max-h-[32rem] divide-y divide-slate-100 overflow-y-auto dark:divide-slate-800">
            {recentBroadcasts.length === 0 ? (
              <p className="px-5 py-4 text-xs text-slate-400">No broadcasts sent yet in this session.</p>
            ) : (
              recentBroadcasts.map((b) => (
                <div key={b.id} className="px-5 py-3">
                  <div className="flex items-center gap-2">
                    <Badge tone={b.kind === "broadcast" ? "navy" : "sky"}>{b.kind}</Badge>
                    <Badge tone={severityTone(b.severity)}>{b.severity}</Badge>
                    {b.delivered ? <Badge tone="green">queued</Badge> : <Badge tone="red">failed</Badge>}
                  </div>
                  <p className="mt-1.5 truncate text-xs font-medium text-slate-800 dark:text-slate-100">{b.title}</p>
                  <p className="mt-0.5 text-[10px] text-slate-400">
                    → {b.audienceLabel} · {relTime(b.at)} · by {b.createdBy}
                  </p>
                  {!b.delivered ? <p className="mt-1 text-[10px] leading-relaxed text-rose-500">{b.deliveryNote}</p> : null}
                </div>
              ))
            )}
          </div>
        </Card>
      </div>

      {/* broadcast dialog */}
      <Dialog
        open={broadcastOpen}
        onClose={() => setBroadcastOpen(false)}
        title="Broadcast to every main-app user"
        footer={
          <div className="flex items-center justify-between gap-3">
            <p className="text-[10px] leading-relaxed text-slate-400">
              Queued on the main sync hub — logged-in browsers receive it within ~20s (notification + toast).
            </p>
            <Button
              variant="navy"
              size="sm"
              loading={busy === "broadcast"}
              disabled={!broadcastForm.title.trim() || !broadcastForm.message.trim()}
              onClick={() =>
                void post("broadcast", {
                  title: broadcastForm.title,
                  message: broadcastForm.message,
                  severity: broadcastForm.severity,
                  linkView: broadcastForm.linkView || undefined,
                }, () => setBroadcastOpen(false))
              }
            >
              <Send className="h-3.5 w-3.5" /> Queue broadcast
            </Button>
          </div>
        }
      >
        <div className="space-y-3">
          <div>
            <FieldLabel htmlFor="bc-title">Title</FieldLabel>
            <Input id="bc-title" value={broadcastForm.title} onChange={(e) => setBroadcastForm((f) => ({ ...f, title: e.target.value }))} placeholder="e.g. Quarterly variance reports due Friday" />
          </div>
          <div>
            <FieldLabel htmlFor="bc-msg">Message</FieldLabel>
            <Textarea id="bc-msg" rows={4} value={broadcastForm.message} onChange={(e) => setBroadcastForm((f) => ({ ...f, message: e.target.value }))} placeholder="Shown as a notification + toast for every logged-in main-app user…" />
          </div>
          <div className="grid grid-cols-2 gap-3">
            <div>
              <FieldLabel htmlFor="bc-sev">Severity</FieldLabel>
              <Select id="bc-sev" value={broadcastForm.severity} onChange={(e) => setBroadcastForm((f) => ({ ...f, severity: e.target.value as Severity }))}>
                <option value="info">info</option>
                <option value="warning">warning</option>
                <option value="critical">critical</option>
              </Select>
            </div>
            <div>
              <FieldLabel htmlFor="bc-view">Deep-link view (optional)</FieldLabel>
              <Input id="bc-view" value={broadcastForm.linkView} onChange={(e) => setBroadcastForm((f) => ({ ...f, linkView: e.target.value }))} placeholder="e.g. #/alerts" />
            </div>
          </div>
        </div>
      </Dialog>

      {/* direct user alert dialog */}
      <Dialog
        open={directOpen}
        onClose={() => setDirectOpen(false)}
        title="Direct alert to one user"
        footer={
          <div className="flex items-center justify-between gap-3">
            <p className="text-[10px] leading-relaxed text-slate-400">
              audience = single user id — only that account receives the notification.
            </p>
            <Button
              variant="primary"
              size="sm"
              loading={busy === "user-alert"}
              disabled={!directForm.userId || !directForm.title.trim() || !directForm.message.trim()}
              onClick={() =>
                void post("user-alert", {
                  title: directForm.title,
                  message: directForm.message,
                  severity: directForm.severity,
                  audience: directForm.userId,
                  audienceLabel: state.users.find((u) => u.id === directForm.userId)?.name ?? directForm.userId,
                }, () => setDirectOpen(false))
              }
            >
              <Send className="h-3.5 w-3.5" /> Send to user
            </Button>
          </div>
        }
      >
        <div className="space-y-3">
          <div>
            <FieldLabel htmlFor="du-user">Recipient</FieldLabel>
            <Select id="du-user" value={directForm.userId} onChange={(e) => setDirectForm((f) => ({ ...f, userId: e.target.value }))} className="w-full">
              <option value="">Select a user…</option>
              {state.users.map((u) => (
                <option key={u.id} value={u.id}>
                  {u.name} — {u.email} ({u.effectiveRole})
                </option>
              ))}
            </Select>
          </div>
          <div>
            <FieldLabel htmlFor="du-title">Title</FieldLabel>
            <Input id="du-title" value={directForm.title} onChange={(e) => setDirectForm((f) => ({ ...f, title: e.target.value }))} placeholder="e.g. Your project needs a variance note" />
          </div>
          <div>
            <FieldLabel htmlFor="du-msg">Message</FieldLabel>
            <Textarea id="du-msg" rows={4} value={directForm.message} onChange={(e) => setDirectForm((f) => ({ ...f, message: e.target.value }))} />
          </div>
          <div>
            <FieldLabel htmlFor="du-sev">Severity</FieldLabel>
            <Select id="du-sev" value={directForm.severity} onChange={(e) => setDirectForm((f) => ({ ...f, severity: e.target.value as Severity }))}>
              <option value="info">info</option>
              <option value="warning">warning</option>
              <option value="critical">critical</option>
            </Select>
          </div>
        </div>
      </Dialog>
    </div>
  );
}
